preset: laravel

risky: false

disabled:
  - concat_without_spaces
  - no_empty_phpdoc
  - no_blank_lines_after_phpdoc
  - ordered_imports
  - function_typehint_space

enabled:
  - concat_with_spaces
  - phpdoc_annotation_without_dot
  - multiline_comment_opening_closing

finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
  name:
    - "*.php"
  not-name:
    - "*.stub"
    - "*.octopy.php"
  depth:
    - "< 3"

