#!/usr/bin/env php
<?php

/**
 *   ___       _
 *  / _ \  ___| |_ ___  _ __  _   _
 * | | | |/ __| __/ _ \| '_ \| | | |
 * | |_| | (__| || (_) | |_) | |_| |
 *  \___/ \___|\__\___/| .__/ \__, |
 *                     |_|    |___/.
 * @author  : Supian M <supianidz@gmail.com>
 * @link    : framework.octopy.id
 * @license : MIT
 */

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to Octopy PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the terminal and delight our users.
|
*/
$app = require 'system/Octopy.php';

/*
|--------------------------------------------------------------------------
| Run The Octopy Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/
$kernel = $app->make(App\Console\Kernel::class);

$status = $kernel->handle(
	$input = $app->make(Octopy\Console\Argv::class, [
		'argv' => $argv
	]),

	$app->make(Octopy\Console\Output::class)
);

$kernel->terminate($input);

die($status);